### ISSUE TITLE
if MicrosoftOCR rotates a PDF 90° then rotate all coordinates 90°

### ISSUE THREAD

**Issue by TungstenRPA** [TungstenTransformation/MicrosoftOCR#44] opened 2024-02-21 09:52 UTC
i hope there is an indication in the header that the page was rotated. if not i might have to examine the x,y coordinates of all words to detection rotation.

**Comment by TungstenTransformation** [comment] 2024-08-01 09:03
duplicate of #42

**Closed by TungstenTransformation** 2024-08-01 09:03 UTC
Labels: bug
